version: '3'
services:
  app:
    image: mock_rest_server:latest
    ports:
      - "3000:3000"
    volumes:
      - ./projects:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    #command: bash -c "tail -f /dev/null"
    command: bash -c "node app.js"